import { characters as authored } from "@/content/characters";
import { CharacterSource } from "@/content/character-schema";
import type { Character, Relation } from "@/content/character-schema";
import { titles, castOf } from "@/content/build";
import { releaseOrder } from "@/lib/graph";
import artRaw from "@/content/character-art.generated.json";

/**
 * CHARACTER ART, not actor photographs.
 *
 * The first version used the most-credited actor's TMDB still, which answers
 * "who played this" on a page that is asking "who is this". Actor stills are
 * still used, in the cast rail and on the "played by" line, where that IS the
 * question. Generated by scripts/sync-characters.ts and committed.
 */
const art = artRaw as Record<
  string,
  { image: string | null; source: "marvel" | "shdb" | "mcu-wiki" | "chosen" | null; matchedAs: string | null }
>;

/**
 * APPEARANCES ARE DERIVED, NEVER TYPED.
 *
 * A character appears in a title if that title's TMDB cast credits name them.
 * The alternative was hand-listing appearances on the character AND cast on the
 * title, which is two sources of truth for one fact. This project has been
 * burned by that twice already: `titleEn` baking in a season range that
 * `seasons` also carried, and `spoilerSafe` living in two files. Both drifted.
 *
 * The join runs off `aliases`, because TMDB credits are written for a poster,
 * not for a database: "Tony Stark", "Logan / Wolverine",
 * "Peter Parker / Spider-Man", "Dr. Otto Octavius". A credit is split on the
 * slash and each part is compared whole against the alias list.
 */

/**
 * WHOLE SEGMENTS ONLY, and that is the entire reason this is not `includes`.
 *
 * Substring matching put Vision in every title crediting "Television", Groot in
 * every "Groot" variant including "Baby Groot" (fine) and "Rocket" in
 * "Rocket Raccoon" (also fine) but also matched "Thor" inside "Thoreau" and
 * "Echo" inside "Echo Base". Normalising and comparing complete segments is
 * both stricter and easier to reason about.
 */
function normalise(s: string): string {
  return s
    .toLowerCase()
    .replace(/[.'’`-]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * "Logan / Wolverine" and "Peter Parker (voice)" both reduce to their names.
 *
 * AND SO DOES A QUOTED NICKNAME, which is where this was losing people.
 *
 * TMDB writes a credit the way it appears on a poster: "James Buchanan 'Bucky'
 * Barnes", "Dr. Henry 'Hank' McCoy", "James 'Rhodey' Rhodes". Stripping the
 * quote marks leaves "james buchanan bucky barnes", which matches no alias
 * anybody would think to write — so Bucky was absent from The First Avenger,
 * Beast from films he is plainly in, and 241 credits matched nobody at all.
 *
 * The alternative was writing every one of those forms into the corpus by hand.
 * A credit is machinery, not a name; teaching the MATCHER to read it fixes all
 * of them at once and cannot drift.
 *
 * Three forms per part, because a nickname can be used either way:
 *   full          james buchanan bucky barnes
 *   without it    james buchanan barnes
 *   nickname+last bucky barnes
 */
function segments(credit: string): string[] {
  const out: string[] = [];
  for (const raw of credit.split("/")) {
    /**
     * A PARENTHETICAL IS OFTEN THE REAL NAME, not a production note.
     *
     * This stripped only `(voice)`, `(uncredited)` and `(archive footage)`,
     * so "Ted (Man-Thing)" stayed one segment reading "ted manthing" and
     * matched nobody — Man-Thing was missing from Werewolf by Night, the film
     * he is the whole last act of. TMDB uses the bracket both ways: to note
     * how a part was performed, and to say who the character actually is.
     *
     * So the brackets come off and BOTH halves are offered — the name outside
     * and the name inside. "Ted (Man-Thing)" yields "ted" and "manthing", and
     * the alias list decides which one means anything.
     */
    const part = raw.replace(/\((?:voice|uncredited|archive[^)]*)\)/gi, "");
    const inner = [...part.matchAll(/\(([^)]+)\)/g)].map((m) => m[1] ?? "");
    for (const x of inner) out.push(normalise(x));
    out.push(normalise(part.replace(/\([^)]*\)/g, " ")));
    out.push(normalise(part));

    const nick = part.match(/['’"]([^'’"]+)['’"]/);
    if (nick) {
      const without = part.replace(/['’"][^'’"]+['’"]/, " ");
      out.push(normalise(without));
      const last = normalise(without).split(" ").filter(Boolean).pop();
      if (last) out.push(normalise(`${nick[1]} ${last}`));
    }
  }
  return out.filter(Boolean);
}

/**
 * AN AGE PREFIX IS NOT A DIFFERENT PERSON — but an exact alias still wins.
 *
 * "Baby Groot" is Groot, and the credit reads that way in Guardians Vol. 2 and
 * in both seasons of the show named after him. The matcher compares whole
 * segments, so it matched none of them and Groot was absent from I Am Groot.
 * That is not one missing alias: thirty-nine credits across the corpus are a
 * known character wearing a qualifier — Young T'Challa, Little Maya, Teen
 * Shang-Chi, Old Apocalypse, Young Matt Murdock.
 *
 * Writing thirty-nine aliases would fix today and rot tomorrow, because the
 * next film will invent a fortieth. Teaching the matcher to read the credit
 * fixes all of them and cannot drift — the same argument that made it read
 * quoted nicknames.
 *
 * THE FALLBACK ONLY FIRES WHEN THE FULL FORM MATCHES NOTHING, and that
 * ordering is the whole safety of it. "Kid Loki" is a real, separate record;
 * stripping first would match Loki as well and hand him his variant's
 * episodes. An exact alias always wins, and the strip is a last resort.
 */
const AGE_PREFIX = /^(?:baby|young|old|teen|kid|little|adult|elderly|future|past) /;

function matchesFor(seg: string): string[] {
  const exact = aliasIndex.get(seg);
  if (exact) return exact;
  const stripped = seg.replace(AGE_PREFIX, "");
  return stripped === seg ? [] : (aliasIndex.get(stripped) ?? []);
}

/** Parsed once, so defaults are filled and nothing downstream sees `undefined`. */
const parsed = authored.map((c) => CharacterSource.parse(c));

const aliasIndex = new Map<string, string[]>();
for (const c of parsed) {
  for (const alias of [c.nameEn, ...c.aliases]) {
    const key = normalise(alias);
    if (!key) continue;
    const list = aliasIndex.get(key) ?? [];
    if (!list.includes(c.id)) list.push(c.id);
    aliasIndex.set(key, list);
  }
}

/**
 * Every character the corpus knows of, with appearances and portrayals filled
 * in from the cast, in release order.
 *
 * Built once at module load. This runs at build time on 147 titles against 84
 * character records; there is no request-time cost because there are no
 * requests.
 */
function build(): Character[] {
  const ordered = releaseOrder(titles);
  const appearances = new Map<string, string[]>();
  const portrayals = new Map<string, Character["portrayals"]>();
  const excluded = new Map(
    parsed.filter((c) => c.notIn.length).map((c) => [c.id, new Set(c.notIn)] as const),
  );
  const fired = new Set<string>();

  for (const t of ordered) {
    /**
     * One title cannot credit the same character twice. Spider-Man: No Way Home
     * credits three Peter Parkers, and without this the title appeared three
     * times in his list. Three PORTRAYALS, one appearance: that distinction is
     * exactly what makes variants visible instead of noisy.
     */
    const seenHere = new Set<string>();
    for (const credit of castOf(t.id)) {
      for (const seg of segments(credit.character)) {
        for (const id of matchesFor(seg)) {
          /* See `notIn` on the schema: the credit uses the word for somebody
             else. Recorded as fired, so a stale exclusion cannot hide. */
          if (excluded.get(id)?.has(t.id)) {
            fired.add(`${id}/${t.id}`);
            continue;
          }
          if (!seenHere.has(id)) {
            seenHere.add(id);
            appearances.set(id, [...(appearances.get(id) ?? []), t.id]);
          }
          /**
           * Deduplicated per actor, per title. A credit reading
           * "Peter Parker / Spider-Man" yields two segments and BOTH match the
           * same character, so without this every such role was recorded twice
           * and No Way Home listed "Tom Holland | Tom Holland |
           * Andrew Garfield | Andrew Garfield".
           */
          const soFar = portrayals.get(id) ?? [];
          if (!soFar.some((x) => x.titleId === t.id && x.actor === credit.actor)) {
            portrayals.set(id, [
              ...soFar,
              { titleId: t.id, actor: credit.actor, actorPhoto: credit.actorPhoto },
            ]);
          }
        }
      }
    }
  }

  /**
   * AN EXCLUSION THAT NO LONGER EXCLUDES ANYTHING IS A LIE ABOUT THE DATA —
   * either the credit was re-typed on TMDB, the alias changed, or somebody
   * pruned an appearance that was real all along. Throwing here is the same
   * rule the poster-wall swaps run under, and for the same reason: a silent
   * no-op is how hand-tuning rots.
   */
  for (const [id, ids] of excluded) {
    for (const titleId of ids) {
      if (fired.has(`${id}/${titleId}`)) continue;
      throw new Error(
        `${id} excludes ${titleId}, but nothing there matches it any more. ` +
          `Re-check the credit — the exclusion is either stale or was wrong.`,
      );
    }
  }

  /**
   * RELATIONS ARE SYMMETRIC, AND ONLY ONE SIDE IS TYPED.
   *
   * Six records named Loki as their `variant` — Sylvie, Kid Loki, Classic Loki,
   * Boastful Loki, Alligator Loki, President Loki — and Loki's own record named
   * one of them. So his page showed a single variant while the multiverse this
   * site exists to model sat one hop away, invisible.
   *
   * Writing both halves by hand is two sources of truth for one fact, which is
   * the failure this corpus has already been burned by three times. The mirror
   * is DERIVED instead: an edge from A to B implies the same edge from B to A,
   * because every kind here is mutual — a variant of me is one I am a variant
   * of, and the same holds for family, ally, enemy, team and host.
   *
   * An authored edge always wins, so a hand-written kind is never overwritten
   * by an inferred one.
   */
  const mirrored = new Map<string, Map<string, Relation["kind"]>>();
  for (const c of parsed) {
    for (const r of c.related) {
      if (!mirrored.has(r.id)) mirrored.set(r.id, new Map());
      mirrored.get(r.id)!.set(c.id, r.kind);
    }
  }

  /**
   * The uncredited ones, folded in and re-sorted so release order still holds.
   * `alsoIn` is the narrow exception documented on the schema; everything else
   * in this map arrived from a credit.
   */
  const releaseIndex = new Map(ordered.map((t, i) => [t.id, i]));
  for (const c of parsed) {
    if (c.alsoIn.length === 0) continue;
    const merged = new Set([...(appearances.get(c.id) ?? []), ...c.alsoIn]);
    appearances.set(
      c.id,
      [...merged].sort(
        (x, y) => (releaseIndex.get(x) ?? 0) - (releaseIndex.get(y) ?? 0),
      ),
    );
  }

  /**
   * A CAMEO ACTOR TAKES EVERY TITLE THAT CREDITS THEM.
   *
   * See `creditedActor` on the schema: the character name is different in all
   * 28 of Stan Lee's appearances, so the join runs on the performer. Release
   * order is preserved because `ordered` is walked in it.
   */
  for (const c of parsed) {
    if (!c.creditedActor) continue;
    const films: string[] = [];
    const played: Character["portrayals"] = [];
    for (const t of ordered) {
      const credit = castOf(t.id).find((x) => x.actor === c.creditedActor);
      if (!credit) continue;
      films.push(t.id);
      played.push({ titleId: t.id, actor: credit.actor, actorPhoto: credit.actorPhoto });
    }
    /* MERGED WITH `alsoIn`, not written over it. This loop runs after the
       uncredited merge, so assigning here silently dropped the one appearance
       that exists precisely because no credit carries it — Stan Lee voicing
       Stan the Janitor across Ultimate Spider-Man. Two derivations feeding one
       field have to combine, never race. */
    const merged = new Set([...films, ...(appearances.get(c.id) ?? [])]);
    appearances.set(
      c.id,
      [...merged].sort(
        (x, y) => (releaseIndex.get(x) ?? 0) - (releaseIndex.get(y) ?? 0),
      ),
    );
    portrayals.set(c.id, played);
  }

  /**
   * A PERFORMANCE IS DERIVED FROM THE SAME CREDITS, KEYED ON THE ACTOR.
   *
   * The three live-action Peters all answer to "Peter Parker", so the alias
   * index cannot separate them and they carry no aliases at all — nothing
   * above this line has given them a single appearance. They get theirs here,
   * from the base character's portrayals filtered to one performer.
   *
   * Which means the split costs nothing in truth: the films are the same films
   * the credits already stated, read one column further across. If Tobey turns
   * up in something new, his record gains it with no edit.
   *
   * RELATIONS ARE COMPUTED THE SAME WAY, AND A CROSSOVER IS NOT EVIDENCE.
   *
   * The first rule was "kept if they share a film", and it was wrong the
   * moment it met No Way Home — a film all three Peters are in. Sharing it
   * proves nothing about whose life anybody belongs to, so it handed Michelle
   * Jones to Tobey and Ned Leeds to Andrew, which is exactly backwards.
   *
   * A title where more than one performance of the same character appears is a
   * CROSSOVER, and a crossover is where the evidence stops. So a claim made in
   * a solo film beats one made only in a crossover: Michelle is in Homecoming,
   * so she is Tom's alone; Mary Jane is in the Raimi films, so she is Tobey's
   * alone; the Green Goblin and Doc Ock are Tobey's, Electro and the Lizard
   * are Andrew's, Vulture and Mysterio are Tom's.
   *
   * Where NOBODY has a solo claim — Aunt May's counterparts, a character who
   * only ever appears in the crossover — everyone who met them keeps them,
   * because then the crossover is the only evidence there is.
   */
  const performerRelations = new Map<string, Relation[]>();
  const castOfTitle = new Map<string, Set<string>>();
  for (const [id, list] of appearances) {
    for (const t of list) {
      if (!castOfTitle.has(t)) castOfTitle.set(t, new Set());
      castOfTitle.get(t)!.add(id);
    }
  }
  const performances = parsed.filter((c) => c.performerOf !== null);
  for (const c of performances) {
    const { character, actor } = c.performerOf!;
    const mine = (portrayals.get(character) ?? []).filter((p) => p.actor === actor);
    appearances.set(c.id, mine.map((p) => p.titleId));
    portrayals.set(c.id, mine);
  }

  /** A title holding more than one performance of the same character. */
  const crossovers = new Set<string>();
  for (const c of performances) {
    for (const t of appearances.get(c.id) ?? []) {
      const others = performances.filter(
        (o) =>
          o.id !== c.id &&
          o.performerOf!.character === c.performerOf!.character &&
          (appearances.get(o.id) ?? []).includes(t),
      );
      if (others.length > 0) crossovers.add(t);
    }
  }

  /** Who this performance met in a film that was NOT a crossover. */
  const soloCast = new Map<string, Set<string>>();
  for (const c of performances) {
    const set = new Set<string>();
    for (const t of appearances.get(c.id) ?? []) {
      if (crossovers.has(t)) continue;
      for (const id of castOfTitle.get(t) ?? []) set.add(id);
    }
    soloCast.set(c.id, set);
  }

  for (const c of performances) {
    const { character } = c.performerOf!;
    /* The base character's own edges: authored, plus the mirrored ones. */
    const base = parsed.find((x) => x.id === character);
    const edges = new Map<string, Relation["kind"]>();
    for (const r of base?.related ?? []) edges.set(r.id, r.kind);
    for (const [id, kind] of mirrored.get(character) ?? new Map()) {
      if (!edges.has(id)) edges.set(id, kind);
    }

    const siblings = performances.filter(
      (o) => o.id !== c.id && o.performerOf!.character === character,
    );
    const met = new Set(
      (appearances.get(c.id) ?? []).flatMap((t) => [...(castOfTitle.get(t) ?? [])]),
    );

    const derived = [...edges]
      .filter(([id, kind]) => {
        if (id === c.id || !met.has(id)) return false;
        if (soloCast.get(c.id)?.has(id)) return true;
        /**
         * AN ENEMY MET IN A CROSSOVER IS STILL YOUR ENEMY.
         *
         * The yield rule below exists because a crossover proves nothing about
         * whose LIFE someone belongs to — being in No Way Home does not make
         * Michelle Jones Tobey's. But it proves everything about who fought
         * whom, because that is what the film is: all three of them against
         * all six villains. Applying the same suspicion to enemies stripped
         * the Sinister Six from every Peter who only met them there.
         *
         * So the crossover is discounted for family, allies and variants, and
         * counted for enemies. You do not acquire someone's family by standing
         * in the room; you do acquire the person swinging at you.
         */
        if (kind === "enemy") return true;
        /* Met only in a crossover. Yield to a sibling with a solo claim. */
        return !siblings.some((o) => soloCast.get(o.id)?.has(id));
      })
      .map(([id, kind]) => ({ id, kind }));

    /**
     * AN AUTHORED EDGE WINS, the same way it does for the mirror.
     *
     * Almost everything about a performance is derived, and it should be. But
     * some facts are true of ONE Peter and false of the others, and no amount
     * of cast data can tell them apart: Gwen Stacy is the woman Andrew's Peter
     * loses, and for the other two the same record means Spider-Gwen, who is a
     * variant. Writing that on the base character makes it wrong twice over.
     *
     * So a performance may author edges. They override the derived kind for an
     * id it already has, and add the ones it cannot derive at all — the three
     * of them being allies, which is true because of a film rather than
     * because of a credit.
     */
    const authoredHere = new Map(c.related.map((r) => [r.id, r.kind]));
    performerRelations.set(c.id, [
      ...derived.map((r) => ({ id: r.id, kind: authoredHere.get(r.id) ?? r.kind })),
      ...[...authoredHere]
        .filter(([id]) => !derived.some((r) => r.id === id) && id !== c.id)
        .map(([id, kind]) => ({ id, kind })),
    ]);
  }

  /**
   * AND THE OTHER HALF OF EVERY PERFORMANCE EDGE.
   *
   * Mary Jane Watson's own page listed Spider-Man and stopped, because the
   * mirror is built from AUTHORED relations and a performance authors almost
   * none. So Tobey's Peter had her and she did not have him — the same
   * one-sided break the mirror was written to fix, reappearing one level down.
   *
   * Mirroring here rather than in the map above keeps the rule identical:
   * an edge from A to B is an edge from B to A, whoever computed it.
   */
  for (const [id, rels] of performerRelations) {
    for (const r of rels) {
      if (!mirrored.has(r.id)) mirrored.set(r.id, new Map());
      if (!mirrored.get(r.id)!.has(id)) mirrored.get(r.id)!.set(id, r.kind);
    }
  }

  return parsed.map((c) => {
    const own = portrayals.get(c.id) ?? [];
    const authored = new Set(c.related.map((r) => r.id));
    const inferred = [...(mirrored.get(c.id) ?? new Map())]
      .filter(([id]) => !authored.has(id) && id !== c.id)
      .map(([id, kind]) => ({ id, kind }));
    return {
      ...c,
      related: c.performerOf
        ? (performerRelations.get(c.id) ?? [])
        : [...c.related, ...inferred],
      appearances: appearances.get(c.id) ?? [],
      portrayals: own,
      /**
       * The portrait is an ACTOR STILL, not a drawing of the character, and the
       * UI says so. Marvel's own API has character art but it is inconsistent
       * and the API is dated; TMDB profile photos are consistent and present.
       *
       * THE MOST-CREDITED ACTOR, not the first one.
       *
       * Taking the first was the obvious reading of "release order puts the
       * earliest first" and it was wrong on sight: the earliest Wolverine is a
       * 1992 animated series, so the grid showed a voice actor nobody
       * recognises, and Spider-Man, Falcon and Captain America were all
       * cartoon voices from the nineties. The screenshot caught it; no
       * assertion could have, because every one of those values was a real
       * photo of a real credited performer.
       *
       * Whoever played the part most often is who people picture. Ties break
       * toward the most recent, because a tie usually means two eras and the
       * later one is the current face.
       */
      image: art[c.id]?.image ?? null,
      artSource: art[c.id]?.source ?? null,
      /** Kept for the "played by" line, which is about the performer. */
      leadActorPhoto: dominantPhoto(own),
    };
  });
}

/**
 * The actor with the most credits for this character, and their photo.
 * `own` arrives in release order, so a later entry wins a tie by overwriting.
 */
function dominantPhoto(own: Character["portrayals"]): string | null {
  const counts = new Map<string, { n: number; photo: string | null }>();
  for (const p of own) {
    const prev = counts.get(p.actor);
    counts.set(p.actor, {
      n: (prev?.n ?? 0) + 1,
      photo: p.actorPhoto ?? prev?.photo ?? null,
    });
  }
  let best: { n: number; photo: string | null } | null = null;
  for (const entry of counts.values()) {
    if (!entry.photo) continue;
    if (!best || entry.n >= best.n) best = entry;
  }
  return best?.photo ?? own.find((p) => p.actorPhoto)?.actorPhoto ?? null;
}

export const allCharacters: Character[] = build();

const byId = new Map(allCharacters.map((c) => [c.id, c]));

export function characterOf(id: string): Character | undefined {
  return byId.get(id);
}

/**
 * EVERYONE GETS A PAGE, including the ones who have never been on screen.
 *
 * This used to filter to `appearances.length > 0`, on the reasoning that a
 * character with no screen credit had nothing to say. That was wrong for
 * exactly the people a reader is most likely to arrive looking for: Eternity,
 * the Living Tribunal, the One Above All, the Beyonder, Mister Sinister —
 * twenty-one names that come up constantly in conversation about Marvel and
 * appear in none of the 167 titles here.
 *
 * Searching for one and getting "no results" reads as "this site does not know
 * what that is". Finding the page and reading "not yet on screen" is a real
 * answer, and it is one only a corpus like this can give. `appearances` stays
 * derived, so nobody has to remember to move anyone when a film finally casts
 * them.
 */
/**
 * THE GRID IS ORDERED BY FAME, AND THE ORDER WAS RESEARCHED.
 *
 * Corpus order is the order records were typed, which put Eternity and the
 * Living Tribunal above Iron Man — arbitrary, and on a page whose first screen
 * decides whether anyone scrolls, arbitrary is the same as wrong.
 *
 * NO METRIC IN THIS REPO PRODUCES THIS LIST. Appearance count puts
 * animated-series regulars above Deadpool; alphabetical puts A-Bomb first.
 * Fame is a fact about the world, not about the data, so it was read off the
 * world — and off more than one source, because any single ranking is one
 * outlet's opinion:
 *
 *   CBR, "35 Most Popular Marvel Characters, Ranked"
 *     https://www.cbr.com/popular-marvel-characters/
 *   iHeart / The Rod Ryan Show, MCU fan poll, February 2025
 *     https://thebuzz.iheart.com/featured/the-rod-ryan-show/content/2025-02-18-the-most-popular-marvel-characters/
 *   Reported monthly search volume, summarised at
 *     https://www.comicbasics.com/fans-rank-top-marvel-comics-superheroes-of-all-time/
 *
 * WHERE THEY DISAGREE the consensus wins, and the disagreements are
 * instructive: the MCU poll has no Wolverine or Magneto worth speaking of and
 * ranks Groot above Black Widow, because it is a poll about films. CBR ranks
 * comics presence and puts Jean Grey and Doctor Doom far higher than any film
 * audience would. This site covers both, so the order sits between them —
 * Spider-Man, Iron Man and Captain America lead every source there is, and
 * Wolverine is top-five on search volume while barely appearing in the MCU
 * poll, so he sits sixth rather than thirtieth.
 *
 * BELOW THE LIST, appearance count takes over. Past the names everyone knows,
 * "how much have they been in" is a reasonable stand-in for "how likely are
 * you to have heard of them", and it needs no maintenance. Ties break
 * alphabetically so the order is stable across builds.
 */
const FAME: string[] = [
  /* Top of every source, in the order all of them agree on. */
  "spider-man", "iron-man", "captain-america", "thor", "hulk", "wolverine",
  /* Carries a film alone, and each is top-fifteen somewhere. */
  "deadpool", "black-panther", "doctor-strange", "loki", "black-widow",
  "thanos", "venom", "scarlet-witch", "groot", "star-lord", "hawkeye",
  "winter-soldier", "nick-fury", "captain-marvel",
  /* Household names from the comics as much as the films. */
  "magneto", "professor-x", "doctor-doom", "green-goblin", "daredevil",
  "punisher", "ant-man", "rocket", "gamora", "vision", "falcon", "war-machine",
  /* The X-Men and Fantastic Four benches, and the street level. */
  "jean-grey", "cyclops", "storm", "mystique", "kingpin", "she-hulk",
  "silver-surfer", "ghost-rider", "mister-fantastic", "invisible-woman",
  "human-torch", "the-thing", "wasp", "nebula", "beast", "nightcrawler",
  "colossus", "rogue",
  /* Known, but a step below — and still ahead of anything by film count. */
  "miles-morales", "gwen-stacy", "ultron", "red-skull", "sentry",
  "adam-warlock", "blade", "moon-knight", "shang-chi", "namor", "hela",
  "killmonger", "vulture", "doctor-octopus", "sandman", "electro", "mysterio",
];

const FAME_RANK = new Map(FAME.map((id, i) => [id, i]));

export const shownCharacters: Character[] = [...allCharacters].sort((a, b) => {
  const ra = FAME_RANK.get(a.id) ?? Infinity;
  const rb = FAME_RANK.get(b.id) ?? Infinity;
  if (ra !== rb) return ra - rb;
  if (a.appearances.length !== b.appearances.length) {
    return b.appearances.length - a.appearances.length;
  }
  return a.nameEn.localeCompare(b.nameEn);
});

/** Has this character ever been credited in anything the corpus holds? */
export function isOnScreen(c: Character): boolean {
  return c.appearances.length > 0;
}

/**
 * Characters credited in a title, IN BILLING ORDER.
 *
 * This used to return them in the corpus's own order, which is the order they
 * happen to be written in `content/characters.ts` — so a Spider-Man film led
 * with Doctor Strange, and every title led with whoever was typed first years
 * ago. On a section headed "who is in this", the answer has to start with
 * whoever the film is about.
 *
 * The film already states that. TMDB's cast list is ordered by billing, and
 * billing is the studio's own answer to "who is this about" — so the lead of
 * every title leads here, with no per-title rule and nothing to keep in sync.
 *
 * A PERFORMANCE inherits the position of the credit naming its own actor,
 * which is what puts the three Peters of No Way Home in the order the poster
 * puts them rather than in corpus order.
 */
export function charactersIn(titleId: string): Character[] {
  const credits = castOf(titleId);

  const rank = new Map<string, number>();
  credits.forEach((credit, i) => {
    for (const seg of segments(credit.character)) {
      for (const id of aliasIndex.get(seg) ?? []) {
        if (!rank.has(id)) rank.set(id, i);
      }
    }
  });
  /* Performances carry no aliases, so they match no credit by name. They take
     the position of the credit their PERFORMER is billed at. */
  for (const c of allCharacters) {
    if (!c.performerOf) continue;
    const i = credits.findIndex((x) => x.actor === c.performerOf!.actor);
    if (i >= 0) rank.set(c.id, i);
  }

  /**
   * A CAMEO GOES LAST, whatever the billing says.
   *
   * Stan Lee is billed 4th in Thor and 60th in Endgame, so ordering purely by
   * credit position put him near the top of some films and the bottom of
   * others — arbitrary, and on a section headed "who is in this" it puts a
   * walk-on above the lead. He is in 44 titles and is the lead of none.
   */
  const cameo = (c: Character) => (c.creditedActor !== null ? 1 : 0);

  return allCharacters
    .filter((c) => c.appearances.includes(titleId))
    .sort(
      (a, b) =>
        cameo(a) - cameo(b) ||
        (rank.get(a.id) ?? 1e6) - (rank.get(b.id) ?? 1e6),
    );
}

/**
 * The filter chips on /characters. Derived from the corpus rather than typed,
 * so a chip can never point at an empty set.
 */
export const CHIPS = [
  { id: "all", match: () => true },
  { id: "hero", match: (c: Character) => c.category === "hero" },
  { id: "villain", match: (c: Character) => c.category === "villain" },
  { id: "mutant", match: (c: Character) => c.mutantClass !== null },
  { id: "avengers", match: (c: Character) => c.affiliation.includes("Avengers") },
  { id: "x-men", match: (c: Character) => c.affiliation.includes("X-Men") },
  { id: "defenders", match: (c: Character) => c.affiliation.includes("Defenders") },
] as const;

export type ChipId = (typeof CHIPS)[number]["id"];
