/**
 * Generates `app/poster-tints.css` from the synced data.
 *
 * The poster placeholder strategy (§14.4) needs a per-title dominant colour so
 * a long grid reads as calm rather than flickery. The obvious way to deliver a
 * per-title value is an inline `style="--poster-tint:#4a1d1d"` — and that is the
 * same trap as the `grid-row: var(--n)` inline style already removed from
 * ThreadPanel. CSP nonces do not cover style ATTRIBUTES, so `style-src` without
 * `unsafe-inline` blocks them; the layout would not break visibly, it would just
 * silently become 130 identical grey boxes, which is the whole placeholder
 * strategy quietly cancelling itself.
 *
 * A generated stylesheet is build-time, cacheable, nonce-able, and keeps R16
 * ("no path page emits an inline style attribute") true.
 *
 * Run by `npm run sync:tmdb`, or on its own with `npm run gen:tints`.
 */

import { writeFile } from "node:fs/promises";
import { titles } from "../content/titles";

interface Synced {
  posterPath: string | null;
  posterTint: string;
}

/**
 * The same `--muted` a title with no poster at all gets. See below for why an
 * authored poster ends up here rather than with a sampled colour.
 */
const NEUTRAL_TINT = "#241414";

export async function generateTintStylesheet(
  generated: Record<string, Synced>,
): Promise<{ rules: number; distinct: number }> {
  /**
   * AUTHORED POSTERS NEED A RULE TOO.
   *
   * The sync is the only source of a sampled colour, and it only has records
   * for titles TMDB knows. One title supplies its own absolute poster URL
   * because no service has a record of it — so it has a poster, renders an
   * `<img>`, and had no `[data-tint]` rule behind it. That is the P2 failure:
   * a poster sitting on a box with no placeholder colour under it.
   *
   * It gets the neutral tint rather than a sampled one. Sampling happens inside
   * the sync, against TMDB, and adding a second sampling path here for a single
   * title would put a network call in a generator that is currently pure. The
   * tint is only visible for the instant before the image decodes.
   */
  const authored = titles
    .filter((t) => t.posterUrl !== null && generated[t.id]?.posterPath == null)
    .map((t): [string, Synced] => [t.id, { posterPath: t.posterUrl, posterTint: NEUTRAL_TINT }]);

  /**
   * A RULE FOR EVERY TITLE, INCLUDING THE ONES WITH NO POSTER.
   *
   * This filtered to titles that HAVE a poster, on the reasonable-sounding
   * logic that a tint is the colour under an image. But a posterless title
   * still renders a poster BOX carrying `data-tint` — it just draws the
   * typographic card instead of an `<img>` — so the box had no colour rule
   * behind it and R20 failed the moment one arrived. The Super Hero Squad Show
   * is the first title in the corpus TMDB has no artwork for at all.
   *
   * Neutral for those, which is exactly what the box wants: a calm ground for
   * the lettering rather than a colour sampled from an image that is not there.
   */
  const withoutPoster = titles
    .filter((t) => t.posterUrl === null && generated[t.id]?.posterPath == null)
    .map((t): [string, Synced] => [t.id, { posterPath: null, posterTint: NEUTRAL_TINT }]);

  const entries = [...Object.entries(generated), ...authored, ...withoutPoster]
    .sort(([a], [b]) => (a < b ? -1 : 1));

  const distinct = new Set(entries.map(([, g]) => g.posterTint)).size;

  const css = [
    "/*",
    " * GENERATED by scripts/gen-tints.ts — do not edit.",
    " * Regenerated by `npm run sync:tmdb`. Committed on purpose: it is content,",
    " * and it must exist at build time without an API key.",
    " *",
    " * One rule per title so the dominant colour can reach the DOM without an",
    " * inline style attribute, which a CSP without `unsafe-inline` would block.",
    " */",
    "",
    ...entries.map(([id, g]) => `[data-tint="${id}"] { --poster-tint: ${g.posterTint}; }`),
    "",
  ].join("\n");

  await writeFile(new URL("../app/poster-tints.css", import.meta.url), css);
  return { rules: entries.length, distinct };
}

// Standalone entry point.
if (import.meta.url === `file://${process.argv[1]}`) {
  const { default: generated } = await import("../content/tmdb.generated.json", {
    with: { type: "json" },
  });
  const { rules, distinct } = await generateTintStylesheet(
    generated as unknown as Record<string, Synced>,
  );
  console.log(`  wrote app/poster-tints.css — ${rules} rules, ${distinct} distinct colours`);
}
