/**
 * THE ICONS, rasterised from the mark and committed.
 *
 *   npm run gen:icons
 *
 * WHY A SCRIPT AND NOT `app/icon.tsx`. Next can generate icons at build time
 * with `ImageResponse`, but that renders HTML — so the mark would have to be
 * rebuilt out of divs, which is a second drawing of the same logo and a second
 * thing to keep in sync. Rasterising the real SVG keeps ONE geometry.
 *
 * WHAT SHIPS, and why each one exists:
 *
 *   app/icon.svg          the tab icon on every modern browser. Vector, so it
 *                         is sharp at any zoom, and it carries a
 *                         `prefers-color-scheme` rule so the rings flip with
 *                         the browser's theme rather than vanishing into it.
 *   app/icon.png          32×32, for the browsers that still ignore SVG icons.
 *   app/apple-icon.png    180×180, opaque. iOS composites a home-screen icon
 *                         onto white if it has an alpha channel, and the white
 *                         rings would disappear — so this one is drawn on the
 *                         site's own near-black ground with real padding.
 *
 * THE OPEN GRAPH CARD IS NOT HERE. It needs type set in two scripts, so it is
 * generated by `app/[locale]/opengraph-image.tsx`, where real fonts are
 * available.
 */

import { writeFile } from "node:fs/promises";
import sharp from "sharp";
import {
  MARK_NODES,
  MARK_THREADS,
  MARK_NODES_SMALL,
  MARK_THREADS_SMALL,
  MARK_RED,
  MARK_R,
  MARK_STROKE,
  type MarkNode,
} from "../app/components/thread-mark";

const SURFACE = "#0a0a0b";
const INK_DARK = "#fafafa";
const INK_LIGHT = "#0a0a0b";

/**
 * The mark as standalone SVG.
 *
 * `ink` is a literal colour rather than `currentColor` here, because nothing
 * outside a document provides one — a favicon and a rasteriser both need the
 * value spelled out.
 */
function markSvg({
  ink,
  size = 64,
  pad = 0,
  background,
  themeAware = false,
  small = false,
}: {
  ink: string;
  size?: number;
  pad?: number;
  background?: string;
  themeAware?: boolean;
  /** The three-node reduction, for anything that lands near 16px. */
  small?: boolean;
}): string {
  const nodeList: MarkNode[] = small ? MARK_NODES_SMALL : MARK_NODES;
  const threadList: string[] = small ? MARK_THREADS_SMALL : MARK_THREADS;
  const box = 64 + pad * 2;
  const style = themeAware
    ? `<style>.ink{stroke:${INK_LIGHT}}` +
      `@media (prefers-color-scheme:dark){.ink{stroke:${INK_DARK}}}</style>`
    : "";
  const bg = background
    ? `<rect width="${box}" height="${box}" rx="${box * 0.22}" fill="${background}"/>`
    : "";
  const threads = threadList
    .map(
      (d) =>
        `<path d="${d}" stroke="${MARK_RED}" stroke-width="${MARK_STROKE}" ` +
        `stroke-linecap="round" fill="none"/>`,
    )
    .join("");
  const nodes = nodeList
    .map((n) => {
      const geom = `cx="${n.cx}" cy="${n.cy}" r="${MARK_R}" stroke-width="${MARK_STROKE}" fill="none"`;
      if (n.red) return `<circle ${geom} stroke="${MARK_RED}"/>`;
      return themeAware
        ? `<circle class="ink" ${geom}/>`
        : `<circle ${geom} stroke="${ink}"/>`;
    })
    .join("");

  return (
    `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" ` +
    `viewBox="0 0 ${box} ${box}" fill="none">${style}${bg}` +
    `<g transform="translate(${pad} ${pad})">${threads}${nodes}</g></svg>`
  );
}

/** The vector favicon, which is the one almost every reader actually sees. */
export const ICON_SVG = markSvg({ ink: INK_DARK, themeAware: true, small: true });

async function main() {
  const here = (name: string) => new URL(`../app/${name}`, import.meta.url);

  await writeFile(here("icon.svg"), ICON_SVG + "\n");

  /* The PNG fallback. Drawn light-on-dark, because a tab strip is dark far
     more often than not and a transparent PNG has no theme rule to fall back
     on — a white-ringed mark survives a light tab better than the reverse. */
  await sharp(Buffer.from(markSvg({ ink: INK_DARK, small: true })))
    .resize(32, 32)
    .png()
    .toFile(new URL(here("icon.png")).pathname);

  /* Opaque, padded, rounded — the home-screen icon. iOS applies its own mask,
     so the padding is what keeps the outer nodes off the corner radius. */
  await sharp(
    Buffer.from(
      markSvg({ ink: INK_DARK, size: 180, pad: 14, background: SURFACE }),
    ),
  )
    .resize(180, 180)
    .png()
    .toFile(new URL(here("apple-icon.png")).pathname);

  console.log("\n  wrote app/icon.svg, app/icon.png, app/apple-icon.png\n");
}

await main();
