/**
 * Writes `docs/COPY-TODO.md` — the editorial review queue.
 *
 * Separate from the sync script because it needs no API key: the copy lives in
 * `content/copy.ts` and the overviews are already committed. Anyone can
 * regenerate the review list without a token.
 *
 * The earlier version of this file said "16 of 130 titles need a human", which
 * read as 114 done when they were 114 wrong — a TMDB synopsis sitting in the
 * always-visible field. It now lists what actually needs doing, and shows the
 * Arabic inline so review is reading one file rather than grepping the corpus.
 *
 *   npm run gen:copy-todo
 */

import { writeFile } from "node:fs/promises";
import { titles } from "../content/titles";
import { spoilerSafe } from "../content/copy";
import generatedRaw from "../content/tmdb.generated.json" with { type: "json" };
import enMessages from "../messages/en.json" with { type: "json" };
import arMessages from "../messages/ar.json" with { type: "json" };

interface Synced {
  overviewEn: string | null;
  overviewAr: string | null;
}
const generated = generatedRaw as unknown as Record<string, Synced>;

/** The same heuristics the sync uses — kept here so both lists agree. */
function arabicNeedsReview(en: string | null, ar: string | null): string | null {
  if (!ar) return "no Arabic overview on TMDB";
  if (ar === en) return "identical to the English";
  if (!/[؀-ۿ]/.test(ar)) return "contains no Arabic script";
  if (/[a-zA-Z]{4,}/.test(ar)) return "contains Latin runs";
  if (ar.length < 40) return "suspiciously short";
  return null;
}

const missingLine = titles.filter((t) => !(t.id in spoilerSafe) && t.spoilerSafe === null);
const contextSuspect = titles
  .map((t) => ({ t, reason: arabicNeedsReview(generated[t.id]?.overviewEn ?? null, generated[t.id]?.overviewAr ?? null) }))
  .filter((x) => x.reason !== null);

/** Every leaf of the message tree, as "path.orderHeading" → text. */
function leaves(obj: unknown, prefix = ""): [string, string][] {
  if (typeof obj === "string") return [[prefix, obj]];
  if (typeof obj !== "object" || obj === null) return [];
  return Object.entries(obj).flatMap(([k, v]) => leaves(v, prefix ? `${prefix}.${k}` : k));
}
const enUi = Object.fromEntries(leaves(enMessages));
const arUi = leaves(arMessages);

const md = [
  "# Copy review",
  "",
  "Generated by `npm run gen:copy-todo`. Do not edit this file — edit",
  "`content/copy.ts` (spoiler-safe lines) or `content/titles.ts` (`context`",
  "overrides), then regenerate. Hand-written copy always wins over anything fetched.",
  "",
  "---",
  "",
  "## 1. Arabic spoiler-safe lines — ALL need a native read",
  "",
  `**${titles.length} lines.** Every one is a draft.`,
  "",
  "`spoilerSafe` is shown to everyone, shield up or down. These were drafted in",
  "English and Arabic together; the English is final, the **Arabic is not**. §6",
  "says test with a real Arabic reader, and that applies to copy as much as to",
  "layout — register, idiom, and diacritics all need a native eye.",
  "",
  "The rule they follow: **setup only, never outcome.** Trailer-level, nothing",
  "past the first act, no deaths or twists or cameos, and no line names another",
  "title (enforced as rule B19).",
  "",
  "| id | English | Arabic |",
  "|---|---|---|",
  ...titles.map((t) => {
    const line = spoilerSafe[t.id];
    return line ? `| \`${t.id}\` | ${line.en} | ${line.ar} |` : `| \`${t.id}\` | — | — |`;
  }),
  "",
  ...(missingLine.length
    ? [
        "### Missing entirely",
        "",
        ...missingLine.map((t) => `- \`${t.id}\` — ${t.titleEn}`),
        "",
      ]
    : []),
  "---",
  "",
  "## 2. Arabic `context` that reads as machine translation",
  "",
  `**${contextSuspect.length} of ${titles.length} titles.**`,
  "",
  "These are the SHIELDED strings, seeded from TMDB's `ar-SA` overview and masked",
  "until a reader taps. They are drafts, not copy to ship — rewrite them as a",
  "`context` override in `content/titles.ts` and the merge will keep your version.",
  "",
  "Lower priority than section 1: nobody sees these unless they ask to.",
  "",
  "| id | title | why |",
  "|---|---|---|",
  ...contextSuspect.map(({ t, reason }) => `| \`${t.id}\` | ${t.titleEn} | ${reason} |`),
  "",
  "---",
  "",
  "## 3. Arabic UI chrome",
  "",
  `**${arUi.length} strings.** Every one is a draft.`,
  "",
  "Interface text — headings, labels, the empty state — from `messages/ar.json`.",
  "Separate from sections 1 and 2 because it is chrome rather than editorial: it",
  "says nothing about any film, so it needs a register check rather than a",
  "spoiler check.",
  "",
  "Plurals are ICU with all six Arabic categories (zero, one, two, few, many,",
  "other). Check the ones marked ⚑ — those are where a wrong category shows up",
  "only at a specific count.",
  "",
  "| key | English | Arabic |",
  "|---|---|---|",
  ...arUi.map(([key, value]) => {
    const flag = /plural/.test(value) ? " ⚑" : "";
    const en = (enUi[key] ?? "").replace(/\|/g, "\\|");
    return `| \`${key}\`${flag} | ${en.replace(/\n/g, " ")} | ${value.replace(/\|/g, "\\|")} |`;
  }),
  "",
].join("\n");

await writeFile(new URL("../docs/COPY-TODO.md", import.meta.url), md);
console.log(
  `  wrote docs/COPY-TODO.md — ${titles.length} AR spoiler-safe lines, ` +
    `${contextSuspect.length} context strings suspect, ${arUi.length} UI strings`,
);
